spring:
  application:
    name: Riyura

  # Supabase DataSource Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    # HikariCP Settings
    hikari:
      maximum-pool-size: 15
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000

  # JPA Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# TMDB Configuration
tmdb:
  api-key: ${TMDB_API_KEY}
  base-url: ${TMDB_BASE_URL:${TMDB_API_BASE_URL}}
  image-base-url: ${TMDB_IMAGE_BASE_URL}

# Supabase Security Configuration
supabase:
  jwt-secret: ${SUPABASE_JWT_SECRET}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    groups-order: ASC
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
  group-configs:
    - group: all
      paths-to-match:
        - /api/**
    - group: profile
      paths-to-match:
        - /api/profile/**
    - group: banner
      paths-to-match:
        - /api/banner/**
    - group: movies
      paths-to-match:
        - /api/movies/**
    - group: tv
      paths-to-match:
        - /api/tv/**
    - group: anime
      paths-to-match:
        - /api/anime/**
